<?php
/**
 * TERYT-API
 *
 * Copyright (c) 2019 pudelek.org.pl
 *
 * @license MIT License (MIT)
 *
 * For the full copyright and license information, please view source file
 * that is bundled with this package in the file LICENSE
 * @author Marcin Pudełek <marcin@pudelek.org.pl>
 */

/**
 * Created by Marcin.
 * Date: 09.09.2017
 * Time: 20:12
 */

namespace Tests\mrcnpdlk\Teryt;

use mrcnpdlk\Teryt\Api;
use mrcnpdlk\Teryt\Client;
use mrcnpdlk\Teryt\Config;
use mrcnpdlk\Teryt\Exception\NotFound;
use mrcnpdlk\Teryt\Model\City;
use mrcnpdlk\Teryt\Model\Commune;
use mrcnpdlk\Teryt\Model\District;
use mrcnpdlk\Teryt\Model\Province;

class ApiTest extends TestCase
{
    /**
     * @var \mrcnpdlk\Teryt\Api
     */
    private $oApi;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $oConfig    = new Config();
        $this->oApi = new Api($oConfig);
    }

    public function testGetCity(): void
    {
        $oResp      = $this->oApi->getCity('0700884');

        $this->assertInstanceOf(City::class, $oResp);
        $this->assertEquals(true, isset($oResp->commune));
        $this->assertInstanceOf(Commune::class, $oResp->commune);
        $this->assertEquals(true, isset($oResp->commune->district));
        $this->assertInstanceOf(District::class, $oResp->commune->district);
        $this->assertEquals(true, isset($oResp->commune->district->province));
        $this->assertInstanceOf(Province::class, $oResp->commune->district->province);
    }

    /**
     * @throws \mrcnpdlk\Teryt\Exception
     * @throws \mrcnpdlk\Teryt\Exception\Connection
     * @throws \mrcnpdlk\Teryt\Exception\InvalidArgument
     * @throws \mrcnpdlk\Teryt\Exception\NotFound
     */
    public function testGetCityNotFound(): void
    {
        $this->expectException(NotFound::class);
        $oResp      = $this->oApi->getCity('0700884000000');
    }
}
